[[redirects]]
  from = "/robots.txt"
  to = "https://raw.githubusercontent.com/faine050/viraltattoo/main/robots.txt"
  status = 200
  force = true
  
[[redirects]]
  from = "/*"
  to = "https://dev-tattoo-viral.pantheonsite.io/:splat"
  status = 200
  force = true
  headers = {X-From = "netlify", X-Custom-Token = "my custom token"}
